/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckDeckIdIndexRouteImport } from './routes/deck/$deckId/index'
import { Route as DeckDeckIdCardNewRouteImport } from './routes/deck/$deckId/card/new'
import { Route as DeckDeckIdCardCardIdRouteImport } from './routes/deck/$deckId/card/$cardId'

const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdIndexRoute = DeckDeckIdIndexRouteImport.update({
  id: '/deck/$deckId/',
  path: '/deck/$deckId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdCardNewRoute = DeckDeckIdCardNewRouteImport.update({
  id: '/deck/$deckId/card/new',
  path: '/deck/$deckId/card/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdCardCardIdRoute = DeckDeckIdCardCardIdRouteImport.update({
  id: '/deck/$deckId/card/$cardId',
  path: '/deck/$deckId/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/redirect': typeof RedirectRoute
  '/widget': typeof WidgetRoute
  '/deck/$deckId/': typeof DeckDeckIdIndexRoute
  '/deck/$deckId/card/$cardId': typeof DeckDeckIdCardCardIdRoute
  '/deck/$deckId/card/new': typeof DeckDeckIdCardNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/redirect': typeof RedirectRoute
  '/widget': typeof WidgetRoute
  '/deck/$deckId': typeof DeckDeckIdIndexRoute
  '/deck/$deckId/card/$cardId': typeof DeckDeckIdCardCardIdRoute
  '/deck/$deckId/card/new': typeof DeckDeckIdCardNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/redirect': typeof RedirectRoute
  '/widget': typeof WidgetRoute
  '/deck/$deckId/': typeof DeckDeckIdIndexRoute
  '/deck/$deckId/card/$cardId': typeof DeckDeckIdCardCardIdRoute
  '/deck/$deckId/card/new': typeof DeckDeckIdCardNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/redirect'
    | '/widget'
    | '/deck/$deckId/'
    | '/deck/$deckId/card/$cardId'
    | '/deck/$deckId/card/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice'
    | '/redirect'
    | '/widget'
    | '/deck/$deckId'
    | '/deck/$deckId/card/$cardId'
    | '/deck/$deckId/card/new'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/redirect'
    | '/widget'
    | '/deck/$deckId/'
    | '/deck/$deckId/card/$cardId'
    | '/deck/$deckId/card/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRoute
  RedirectRoute: typeof RedirectRoute
  WidgetRoute: typeof WidgetRoute
  DeckDeckIdIndexRoute: typeof DeckDeckIdIndexRoute
  DeckDeckIdCardCardIdRoute: typeof DeckDeckIdCardCardIdRoute
  DeckDeckIdCardNewRoute: typeof DeckDeckIdCardNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/': {
      id: '/deck/$deckId/'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId/'
      preLoaderRoute: typeof DeckDeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/card/new': {
      id: '/deck/$deckId/card/new'
      path: '/deck/$deckId/card/new'
      fullPath: '/deck/$deckId/card/new'
      preLoaderRoute: typeof DeckDeckIdCardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/card/$cardId': {
      id: '/deck/$deckId/card/$cardId'
      path: '/deck/$deckId/card/$cardId'
      fullPath: '/deck/$deckId/card/$cardId'
      preLoaderRoute: typeof DeckDeckIdCardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRoute,
  RedirectRoute: RedirectRoute,
  WidgetRoute: WidgetRoute,
  DeckDeckIdIndexRoute: DeckDeckIdIndexRoute,
  DeckDeckIdCardCardIdRoute: DeckDeckIdCardCardIdRoute,
  DeckDeckIdCardNewRoute: DeckDeckIdCardNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
